version: '3.7'

services:
    php_app: 
      image: php:8.1-apache 
      container_name: php_app
      ports: 
        - 80:80
      volumes:
      - ./src:/var/www/html
      - ./apache2/sites-enabled:/etc/apache2/sites-enabled
      - ./php:/usr/local/etc/php/conf.d